<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0.1 (Python 3.10.12 on linux)" generated="2024-11-25T20:57:11.817092" rpa="false" schemaversion="5">
<suite id="s1" name="Login" source="/home/condabu/development/dashqa/testrunner/suites/Omni/Login">
<suite id="s1-s1" name="Login" source="/home/condabu/development/dashqa/testrunner/suites/Omni/Login/Login.robot">
<test id="s1-s1-t1" name="Verify whether the Customer able to Login into Coop Bank application with valid Username and Password" line="8">
<kw name="Launch Application" owner="common_keywords">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2024-11-25T20:57:11.975120" level="INFO">Opening browser 'headlesschrome' to base url 'https://condabu.com'.</msg>
<msg time="2024-11-25T20:57:20.802752" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ad8bcbe4040&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2b6358f86a8ac1947fadf760dd3f1ecc/screenshot</msg>
<msg time="2024-11-25T20:57:20.806216" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ad8bcbe42e0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2b6358f86a8ac1947fadf760dd3f1ecc/screenshot</msg>
<msg time="2024-11-25T20:57:20.809690" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ad8bcbe4460&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2b6358f86a8ac1947fadf760dd3f1ecc/screenshot</msg>
<msg time="2024-11-25T20:57:20.813943" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=44393): Max retries exceeded with url: /session/2b6358f86a8ac1947fadf760dd3f1ecc/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ad8bcbe45e0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<arg>${URL}</arg>
<arg>headlesschrome</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="FAIL" start="2024-11-25T20:57:11.974523" elapsed="8.841897">Execution terminated by signal</status>
</kw>
<kw name="Maximize Browser Window" owner="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="NOT RUN" start="2024-11-25T20:57:20.817578" elapsed="0.000125"/>
</kw>
<kw name="Sleep" owner="BuiltIn">
<arg>30s</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" start="2024-11-25T20:57:20.818200" elapsed="0.000106"/>
</kw>
<status status="FAIL" start="2024-11-25T20:57:11.971787" elapsed="8.846866">Execution terminated by signal</status>
</kw>
<kw name="Page Should Contain" owner="SeleniumLibrary">
<arg>condabu</arg>
<doc>Verifies that current page contains ``text``.</doc>
<status status="NOT RUN" start="2024-11-25T20:57:20.819291" elapsed="0.000192"/>
</kw>
<doc>This test case verifies that a user can log in with valid credentials.</doc>
<tag>Login</tag>
<tag>Smoke</tag>
<status status="FAIL" start="2024-11-25T20:57:11.960955" elapsed="8.859239">Execution terminated by signal</status>
</test>
<status status="FAIL" start="2024-11-25T20:57:11.840022" elapsed="8.998168"/>
</suite>
<status status="FAIL" start="2024-11-25T20:57:11.818189" elapsed="9.021817"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">Login</stat>
<stat pass="0" fail="1" skip="0">Smoke</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Login">Login</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Login">Login.Login</stat>
</suite>
</statistics>
<errors>
<msg time="2024-11-25T20:57:20.802752" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ad8bcbe4040&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2b6358f86a8ac1947fadf760dd3f1ecc/screenshot</msg>
<msg time="2024-11-25T20:57:20.806216" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ad8bcbe42e0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2b6358f86a8ac1947fadf760dd3f1ecc/screenshot</msg>
<msg time="2024-11-25T20:57:20.809690" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ad8bcbe4460&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2b6358f86a8ac1947fadf760dd3f1ecc/screenshot</msg>
<msg time="2024-11-25T20:57:20.813943" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=44393): Max retries exceeded with url: /session/2b6358f86a8ac1947fadf760dd3f1ecc/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7ad8bcbe45e0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
</errors>
</robot>
