<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0.1 (Python 3.10.12 on linux)" generated="2024-11-25T22:53:23.381736" rpa="false" schemaversion="5">
<suite id="s1" name="Omni" source="/home/condabu/development/dashqa/testrunner/suites/Omni">
<suite id="s1-s1" name="Login" source="/home/condabu/development/dashqa/testrunner/suites/Omni/Login">
<suite id="s1-s1-s1" name="Login" source="/home/condabu/development/dashqa/testrunner/suites/Omni/Login/Login.robot">
<test id="s1-s1-s1-t1" name="Verify whether the Customer able to Login into Coop Bank application with valid Username and Password" line="8">
<kw name="Launch Application" owner="common_keywords">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2024-11-25T22:53:23.533099" level="INFO">Opening browser 'headlesschrome' to base url 'https://condabu.com'.</msg>
<msg time="2024-11-25T22:53:25.258049" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7670d5158130&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76866232ba3bc5e92006fe776683201c/screenshot</msg>
<msg time="2024-11-25T22:53:25.259155" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7670d51581f0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76866232ba3bc5e92006fe776683201c/screenshot</msg>
<msg time="2024-11-25T22:53:25.260289" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7670d5158370&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76866232ba3bc5e92006fe776683201c/screenshot</msg>
<msg time="2024-11-25T22:53:25.261201" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=52533): Max retries exceeded with url: /session/76866232ba3bc5e92006fe776683201c/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7670d51584f0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<arg>${URL}</arg>
<arg>headlesschrome</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="FAIL" start="2024-11-25T22:53:23.532504" elapsed="1.729001">Execution terminated by signal</status>
</kw>
<kw name="Maximize Browser Window" owner="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="NOT RUN" start="2024-11-25T22:53:25.261956" elapsed="0.000095"/>
</kw>
<kw name="Sleep" owner="BuiltIn">
<arg>30s</arg>
<doc>Pauses the test executed for the given time.</doc>
<status status="NOT RUN" start="2024-11-25T22:53:25.262384" elapsed="0.000082"/>
</kw>
<status status="FAIL" start="2024-11-25T22:53:23.531112" elapsed="1.731898">Execution terminated by signal</status>
</kw>
<kw name="Page Should Contain" owner="SeleniumLibrary">
<arg>condabu</arg>
<doc>Verifies that current page contains ``text``.</doc>
<status status="NOT RUN" start="2024-11-25T22:53:25.263512" elapsed="0.000116"/>
</kw>
<doc>This test case verifies that a user can log in with valid credentials.</doc>
<tag>Login</tag>
<tag>Smoke</tag>
<status status="FAIL" start="2024-11-25T22:53:23.519236" elapsed="1.744869">Execution terminated by signal</status>
</test>
<status status="FAIL" start="2024-11-25T22:53:23.403197" elapsed="1.877209"/>
</suite>
<status status="FAIL" start="2024-11-25T22:53:23.402172" elapsed="1.879931"/>
</suite>
<suite id="s1-s2" name="PesaLink" source="/home/condabu/development/dashqa/testrunner/suites/Omni/PesaLink">
<suite id="s1-s2-s1" name="PesalinkToMobile" source="/home/condabu/development/dashqa/testrunner/suites/Omni/PesaLink/PesalinkToMobile.robot">
<test id="s1-s2-s1-t1" name="Customer can use pesalini whether the Customer Coop Bank application with valid Username and Password" line="8">
<doc>This test case verifies that a user can log in with valid credentials.</doc>
<tag>regression</tag>
<tag>robot:exit</tag>
<status status="FAIL" start="2024-11-25T22:53:25.286184" elapsed="0.013429">Test execution stopped due to a fatal error.</status>
</test>
<status status="FAIL" start="2024-11-25T22:53:25.284907" elapsed="0.031497"/>
</suite>
<status status="FAIL" start="2024-11-25T22:53:25.283680" elapsed="0.034277"/>
</suite>
<status status="FAIL" start="2024-11-25T22:53:23.382719" elapsed="1.936805"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0" info="combined" combined="NOT robot:exit">NOT robot:exit</stat>
<stat pass="0" fail="1" skip="0">Login</stat>
<stat pass="0" fail="1" skip="0">regression</stat>
<stat pass="0" fail="1" skip="0">Smoke</stat>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="Omni">Omni</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Login">Omni.Login</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1" name="Login">Omni.Login.Login</stat>
<stat pass="0" fail="1" skip="0" id="s1-s2" name="PesaLink">Omni.PesaLink</stat>
<stat pass="0" fail="1" skip="0" id="s1-s2-s1" name="PesalinkToMobile">Omni.PesaLink.PesalinkToMobile</stat>
</suite>
</statistics>
<errors>
<msg time="2024-11-25T22:53:25.258049" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7670d5158130&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76866232ba3bc5e92006fe776683201c/screenshot</msg>
<msg time="2024-11-25T22:53:25.259155" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7670d51581f0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76866232ba3bc5e92006fe776683201c/screenshot</msg>
<msg time="2024-11-25T22:53:25.260289" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7670d5158370&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/76866232ba3bc5e92006fe776683201c/screenshot</msg>
<msg time="2024-11-25T22:53:25.261201" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=52533): Max retries exceeded with url: /session/76866232ba3bc5e92006fe776683201c/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7670d51584f0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
</errors>
</robot>
